#!/bin/bash
#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
if ! test -e /var/run/docker.sock
then echo "Please launch this image with the option -v //var/run/docker.sock:/var/run/docker.sock"
     exit 1
fi
# launch traefik
(
 while [ 1 ]
 do /sbin/traefik -c /etc/traefik.toml
 done
)&
# wait for readyness then deploy actions
(
 if test -f /app/actions/manifest.yaml
 then
   waitready
   cd /app/actions
   wsk project deploy
 fi
)&
DOCKER_NETWORK=$(docker inspect $(hostname) -f "{{json .NetworkSettings.Networks}}" | jq -r 'keys[0]')
JVM_ARGS="-Dconfig.override_with_env_vars=true\
 -Dwhisk.standalone.docker.network=${DOCKER_NETWORK:-bridge}\
 -Dwhisk.standalone.host.name=localhost\
 -Dwhisk.standalone.host.ip=$(hostname -i)\
 -Dwhisk.standalone.proxy.port=3280\
 -Dwhisk.standalone.proxy.url=http://localhost:3280 $JVM_EXTRA_ARGS"
set -x
java $JVM_ARGS -jar openwhisk-standalone.jar --no-browser "$@"
